;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		LaTeX-babel-insert-hyphen
		LaTeX-insert-left-brace
		TeX-insert-backslash
		haml-electric-backspace
		my-backward-delete-word
		prelude-move-beginning-of-line
		yaml-electric-backspace
		yaml-electric-dash-and-dot
		))

(setq mc/cmds-to-run-once
      '(
		))
